### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by patandrick**
removed me(patrick)

### CODE REVIEW

**Comment by patandrick** [comment]
:+1:

**Comment by harti2006** [comment]
Thank you for all your contributions. All the best for your future!

**Comment by harti2006** [comment]
:+1:

**Comment by patandrick** [comment]
Thanks @harti2006. Same to you. Was a pleasure to work with you guys. :)

**Comment by mrandi** [comment]
👍

**Pull request merged**
