### PR TITLE
Add component to display any errors that happen because of bad user input

### LINKED ISSUE #281: Filter errors are not being shown
When an error to the filter occurs, it is not obvious what the issue might be. We should add a box that displays the resulting error message from JQ.

## Expected Behaviour

Add a box next to the filter input to display any error messages that might occur.

## Current Behaviour

No errors are being displayed

## Context

I'd like to know when my filter input is wrong and any helpful info on what needs fixed.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by bbbco**
One of the things that has bugged me about this extension is #281 and this PR should fix that.

Feel free to discuss styling / positioning of the error message. Here's a screenshot of the current view:

Selection_295

fixes #281

### CODE REVIEW

**Comment by mrandi** [comment]
:+1:

**Comment by mrandi** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

**Comment by mrandi** [comment]
@bbbco I think we miss an errors.tsx file, could it be?

**Comment by bbbco** [comment]
Yeah, I'm sorry. I just pushed it up to my branch. I'll open a new MR

**Comment by mrandi** [comment]
no problem :D I added now also travis to at least build before merging :)
thx for the contribution again!

**Pull request merged**
