### PR TITLE
fix typo in Readme.md

### PR DESCRIPTION
**Pull request by raphaeleidus**
there was a small typo in the readme. This fixes it.

### CODE REVIEW

**Comment by patandrick** [comment]
Please be so kind and observe the checks.
Title and description must have more than 8 characters.

**Comment by raphaeleidus** [comment]
@patandrick it would be good if CONTRIBUTING.md referenced that. I looked at if before making my PR.

**Comment by mrandi** [comment]
:+1:

**Comment by patandrick** [comment]
👍

**Comment by patandrick** [comment]
We will take care of it @raphaeleidus 
Thank you for your contribution and help.

**Comment by mrandi** [comment]
@raphaeleidus here the PR :) Thx!

**Pull request merged**
