### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by patandrick**
change email address of Patrick (me)
added Andre @harti2006 
removed inactive maintainers

### CODE REVIEW

**Comment by patandrick** [comment]
:+1:

**Comment by patandrick** [comment]
👍

**Comment by mrandi** [comment]
👎 plz update the info adding @harti2006 and remove old members, thx

**Comment by patandrick** [comment]
:+1:

**Comment by mrandi** [comment]
👍

**Comment by patandrick** [comment]
👍

**Pull request merged**
