### PR TITLE
Preact Port (WORK IN PROGRESS)

### PR DESCRIPTION
**Pull request by raphaeleidus**
This is a sample of what the codebase would look like in Preact or React
When looking over the code ignore `src/ts/App/Components/aceEditor.tsx` I copied that component in from react-ace and then added static typing. Found like 5 bugs while typing it, lol.
But it is like half the PR because it exposes the entire API of Brace

### CODE REVIEW

**Comment by mrandi** [comment]
Thanks a lot for your help!!

**Comment by mrandi** [comment]
Link to issue https://github.com/zalando-incubator/bro-q/issues/91

**Comment by artdaw** [comment]
@raphaeleidus, first of all I'd like to thank you for your contribution! I can support you in this important PR.
I have a couple of questions:
1. Why do you decide to copy aceEditor? IMHO it's an overhead because:
  a. we need support every update of Ace Editor
  b. if they fix a bug we need to keep an eye on announcements
  c. there is no way to check possible vulnerabilities with `npm audit`
  d. there is already [react-ace](https://github.com/securingsincity/react-ace), maybe we can use it?

2. You said `"But it is like half the PR"`, do you have some kind of plan or list of things to do in this PR? It would be awesome if you share it here, so I can help.

**Comment by artdaw** [comment]
this PR is closed in favour of https://github.com/zalando-incubator/bro-q/pull/167.

**Pull request closed without merging**
