### PR TITLE
fix css & html issues

### LINKED ISSUE #6: bro-q appearing in the middle of the page although it should not
## Expected Behaviour
the page https://www.postgresql.org/docs/current/static/monitoring.html opens without bro-q popping up at the bottom.

image

## Current Behaviour
the page https://www.postgresql.org/docs/current/static/monitoring.html has at the bottom bro-q attached, which should not be.

image

## Steps to Reproduce (for bugs)
go to the page https://www.postgresql.org/docs/current/static/monitoring.html with bro-q enabled

## Context
its not affecting the use of the website much, but it disturbs. also i'm wondering if it happens on other pages as well.

## Your Environment
https://www.whatismybrowser.com/w/R9JYPJN

### PR DESCRIPTION
**Pull request by patandrick**
- fixed css style (output editor rendering)

- implemented check for childnodes length and prenode nodename

testing release:
[release-testing-1.2.0.zip](https://github.com/zalando-incubator/bro-q/files/1937717/release-testing-1.2.0.zip)

fixes #6

### CODE REVIEW

**Comment by patandrick** [comment]
:+1:

**Comment by patandrick** [comment]
:+1:

**Comment by mrandi** [comment]
@drummerwolli are you so kind to test this out?

**Comment by patandrick** [comment]
:+1:

**Comment by mrandi** [comment]
:+1:

**Comment by drummerwolli** [comment]
the issue with the reported site is gone for me 👍

**Pull request merged**
