### PR TITLE
Add loading bar to top of screen

### PR DESCRIPTION
**Pull request by bbbco**
This PR fixes https://github.com/zalando-incubator/bro-q/issues/291 by adding an absolutely positioned CSS animated loading bar to the top of the screen whenever a new filter is applied. After the filter has rendered, the loading bar is removed from the screen.

### CODE REVIEW

**Comment by mrandi** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

**Comment by mrandi** [comment]
:+1:

**Comment by mrandi** [comment]
@bbbco thx! 🎉

**Comment by bbbco** [comment]
No problem!

**Pull request merged**
