### PR TITLE
Add hide/show unfiltered json button

### PR DESCRIPTION
**Pull request by akread**
Also includes an option for default behavior on load.

screen shot 2018-08-06 at 8 23 13 am
screen shot 2018-08-06 at 8 23 22 am
screen shot 2018-08-06 at 8 23 31 am

### CODE REVIEW

**Comment by raphaeleidus** [comment]
hey @akread  this is great.
In the discussion here: https://github.com/zalando-incubator/bro-q/issues/93
It was suggested that if there is no filter at all just show the original input.
Do you think this PR would be easy to extend to have "Single Panel View" available for both input and output?

**Comment by akread** [comment]
If you hide the unfiltered json by default that is essentially what you will have. On load you will only see one panel with the default query (which is the entire json object).

Does that suffice or are we envisioning something else?

**Comment by raphaeleidus** [comment]
my question is more around how hard would it be to extend to allow manual toggling back and forth so if you do have a filter you could still go to full screen.

But this looks good to me as is.

**Comment by mrandi** [comment]
:+1:

**Comment by mrandi** [comment]
the same for me :) thank you both!

**Comment by anstit** [comment]
Thanks, this looks great!

**Comment by anstit** [comment]
:+1:

**Pull request merged**
