### PR TITLE
Apply Preact implementation

### PR DESCRIPTION
**Pull request by mrandi**
complete https://github.com/zalando-incubator/bro-q/pull/95

### CODE REVIEW

**Comment by artdaw** [comment]
@mrandi @patandrick I'm gonna finish this huge PR this week, so we can deploy cause there will be more conflicts.

**Comment by artdaw** [comment]
@mrandi I think this PR is ready for review. Also I noticed that some new functionality like liveUrlQuery is not integrated here, so you decide: we integrate it in this PR or somehow later.

**Comment by mrandi** [comment]
:+1:

**Comment by ChristianLohmann** [comment]
:+1:

**Comment by artdaw** [comment]
@mrandi do you mean merge this PR?

**Comment by mrandi** [comment]
@artdaw yes exactly :)

**Pull request merged**
